<a href="https://colab.research.google.com/github/QaziSaim/DataToolKitSharpen/blob/main/NumpyAdvance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
arr = np.ones((3,4)) # to calculate inverse of matrix np.eye used
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(arr)

In [13]:
df.head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [14]:
import random

In [19]:
random.choice((1,2,4,5,6,4))

6

In [20]:
random.choice('Sahim')

'S'

In [24]:
random.randrange(1,1000,10)

781

In [25]:
random.random()

0.5735342406082659

In [27]:
lis = [1,2,3,4,5]
random.shuffle(lis)

In [28]:
lis

[5, 1, 4, 3, 2]

In [31]:
# distribution
random.uniform(7,14)

9.02364320144796

In [32]:
np.random.rand(2,3)

array([[0.7061059 , 0.84261635, 0.27202919],
       [0.81259138, 0.81542275, 0.62143586]])

In [33]:
np.random.rand(1)

array([0.8141726])

In [35]:
np.random.randn(2,3) # uniform distribution

array([[ 1.33846192, -0.12575358,  0.50526423],
       [-0.34773037,  0.43747908,  0.57955968]])

In [38]:
np.random.random_sample() # between 0 and 1 : 1 exclude called half interval [ is inclusiev )- exclusive

0.9823808456815974

In [39]:
np.random.randint(1,5,size=(3,4))

array([[4, 1, 2, 4],
       [2, 3, 2, 3],
       [3, 3, 4, 2]])

In [40]:
arr = np.random.randint(1,5,size=(3,4))

In [41]:
arr.shape

(3, 4)

In [42]:
arr.size

12

In [43]:
arr.ndim

2

In [44]:
arr

array([[2, 3, 2, 1],
       [2, 4, 4, 2],
       [1, 4, 3, 3]])

In [47]:
arr.reshape(2,6) # array size cannot change: multiple of size

array([[2, 3, 2, 1, 2, 4],
       [4, 2, 1, 4, 3, 3]])

In [50]:
arr.reshape(1,12)

array([[2, 3, 2, 1, 2, 4, 4, 2, 1, 4, 3, 3]])

In [53]:
arr.reshape(2,-1) # pass -1 by default it consider it -1 only try

array([[2, 3, 2, 1, 2, 4],
       [4, 2, 1, 4, 3, 3]])

In [56]:
arr.reshape(12,1).base # back to original shape

array([[2, 3, 2, 1],
       [2, 4, 4, 2],
       [1, 4, 3, 3]])

In [57]:
# to make dimension change
arr.reshape(2,2,3) # 2,2 new dimension, 2 dim, 2 col, 3 row

array([[[2, 3, 2],
        [1, 2, 4]],

       [[4, 2, 1],
        [4, 3, 3]]])

In [58]:
arr.reshape(3,2,2)

array([[[2, 3],
        [2, 1]],

       [[2, 4],
        [4, 2]],

       [[1, 4],
        [3, 3]]])

In [63]:
arr.reshape(1,2,2,3)

array([[[[2, 3, 2],
         [1, 2, 4]],

        [[4, 2, 1],
         [4, 3, 3]]]])

In [67]:
# arr.reshape(2,2,3,1,1,1,1,1,1,1)

In [70]:
np.zeros((1,1,3,4)) # number of one add increase one dim

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])