<a href="https://colab.research.google.com/github/QaziSaim/DataToolKitSharpen/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
# numpy is built on c++
# why numpy is fastest: because of array
# interview : why numpy is faster and use in data analytics and use in data science

In [ ]:
l = [1,2,3,4,5]

In [ ]:
np.array(l)

array([1, 2, 3, 4, 5])

In [ ]:
type(l)

list

In [ ]:
# ndarray meanns ndimensional array it can be 1 2 3 or n dim
# array is way numpy store the data, : is a container data: store only same type of datatype:
# store only homogenious data

In [ ]:
l = [1,2,3,4,"Rishi"]
arr = np.array(l)


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr

array(['1', '2', '3', '4', 'Rishi'], dtype='<U21')

In [ ]:
# if one element is string entire data become string
arr.ndim

1

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
l = [1,2,3,4]

In [ ]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [ ]:
# matrix will be bydefaul 3d

In [ ]:
try:
  np.matrix([[[1,2],[5,6],[7,8]]])
except:
  print("Error")

Error


In [ ]:
# matrix is a subclass of array

In [ ]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.asanyarray([[[1,2],[3,4],[5,6]]]) # it also convert array but not convert the array subclass :if it already subclass of array it will not convert

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
mat = np.matrix([[1,2],[2,3]])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2],
        [2, 3]])

In [ ]:
t = ([1,2,3],[4,5,6])

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# earlier np.asarray used but now array used
np.asarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = 5
np.array(a)

array(5)

In [ ]:
# second half

In [ ]:
l = [1,2,3,4,5]

In [ ]:
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]

np.int64(1)

In [ ]:
arr[3]

np.int64(4)

In [ ]:
a = arr

In [ ]:
a[0] = 1000

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
# Deep Copy and Shallow Copy : Shallow both variable point same object: deep copy both variable have different address

In [ ]:
b = a.copy()

In [ ]:
b[0] = 231

In [ ]:
a

array([1000,    2,    3,    4,    5])

In [ ]:
b

array([231,   2,   3,   4,   5])

In [ ]:
# to create array, >>> array, asarray, asanyarray, deep copy, shallow copy

In [ ]:
# There are multiple way to generate array

In [ ]:
np.fromfunction(lambda i,j : i==j, shape = (3,3)) # from any function

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr1 = np.fromfunction(lambda i,j : i*j,(3,3)) # from any function

In [ ]:
arr1.shape

(3, 3)

In [ ]:
arr.shape

(5,)

In [ ]:
arr1.size # no of element

9

In [ ]:
arr1

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in np.arange(5.5):
  print(i)

0.0
1.0
2.0
3.0
4.0
5.0


In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [ ]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7935fd88b510>

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('12 13 14',sep = " ") # it by default float

array([12., 13., 14.])

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(0,5)

range(0, 5)

In [ ]:
# Demerit of range it require only non float value

In [ ]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [ ]:
np.linspace(1,5,20) # start 1 end 5 vlaue 20

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10,base=10)# give and convert into log base 2

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr3= np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [ ]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
np.ones(1)

array([1.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
arr4 = np.zeros((1,3,3,4))
arr4.shape

(1, 3, 3, 4)

In [ ]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr = np.ones((3,4))

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr * 10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [ ]:
# what is numpy
# array
# list vs array
# whay array is faster then list?
# homogenous, memory allocation
# concept of refresensing ,
# concept of resizing
# array statically define , not dynamic,
# vectorization